---
- import_tasks: upload.yml
- import_tasks: configure.yml
- name: add system module
  shell: ./metricbeat modules enable system chdir={{ base_dir }}/metricbeat

- name: start metricbeat
  shell: systemctl daemon-reload && systemctl start metricbeat