---
- name: judge a filebeat dir is exits
  shell: ls {{ base_dir }}/filebeat
  ignore_errors: True
  register: result

- debug: var=result.failed

- name: Unarchive filebeat tar to target machine
  unarchive: 
    src: "{{ source_tar_file_directory }}/filebeat-7.12.1-linux-x86_64.tar.gz"
    dest: "{{ base_dir }}"
  when: result.failed

- name: Rename filebeat directory name
  command: mv {{ base_dir }}/filebeat-7.12.1-linux-x86_64 {{ base_dir }}/filebeat
  when: result.failed

